import { useEffect, useState } from 'react';
import type { ChannelingGovernanceStatus, ChannelingProject } from '../lib/channelingProjectStore';

const statusLabels: Record<ChannelingGovernanceStatus, string> = { identified: '识别', confirmed: '确认', governing: '治理', verifying: '验证', closed: '关闭', recurred: '复发' };
const today = () => new Date().toISOString().slice(0, 10);
type Props = { canEdit: boolean };

export function ChannelingProjectManagement({ canEdit }: Props) {
  const [projects, setProjects] = useState<ChannelingProject[]>([]);
  const [todos, setTodos] = useState<(ChannelingProject & { overdue: boolean })[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [message, setMessage] = useState('');
  const [newProject, setNewProject] = useState({ projectName: '', block: '', owner: '' });
  const selected = projects.find((item) => item.id === selectedId);
  const load = async () => {
    const [projectResponse, todoResponse] = await Promise.all([fetch('/api/channeling-projects'), fetch(`/api/channeling-projects/pending?date=${today()}`)]);
    const [projectPayload, todoPayload] = await Promise.all([projectResponse.json(), todoResponse.json()]);
    if (projectPayload.success) { setProjects(projectPayload.data); setSelectedId((id) => id ?? projectPayload.data[0]?.id ?? null); }
    if (todoPayload.success) setTodos(todoPayload.data);
  };
  useEffect(() => { void load().catch(() => setMessage('项目加载失败')); }, []);
  const request = async (url: string, init: RequestInit) => { const response = await fetch(url, init); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message || '操作失败'); return payload.data; };
  const save = async (changes: Record<string, unknown>) => { if (!selected) return; try { await request(`/api/channeling-projects/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); await load(); setMessage('治理台账已保存'); } catch (error: any) { setMessage(error.message); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await request('/api/channeling-projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newProject) }); setNewProject({ projectName: '', block: '', owner: '' }); await load(); setSelectedId(created.id); } catch (error: any) { setMessage(error.message); } };
  return <div className="page-stack">
    <section className="app-card p-5"><h3 className="section-title">注窜项目台账（治理闭环）</h3><p className="mt-1 text-sm text-slate-500">识别、确认、治理、验证、关闭与复发全流程留痕；待办按风险、超期、损失和影响井数排序。</p>{message && <p className="status-banner status-banner-info mt-3">{message}</p>}
      {canEdit && <form className="mt-4 grid gap-2 md:grid-cols-4" onSubmit={create}><input className="field-control" required placeholder="项目名称" value={newProject.projectName} onChange={(e) => setNewProject({ ...newProject, projectName: e.target.value })}/><input className="field-control" required placeholder="区块" value={newProject.block} onChange={(e) => setNewProject({ ...newProject, block: e.target.value })}/><input className="field-control" required placeholder="责任人" value={newProject.owner} onChange={(e) => setNewProject({ ...newProject, owner: e.target.value })}/><button className="action-button action-primary">新增项目</button></form>}</section>
    <section className="grid gap-4 lg:grid-cols-[300px_1fr]"><aside className="app-card p-4"><h4 className="font-bold">治理待办</h4><div className="mt-3 space-y-2">{todos.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded border p-3 text-left text-sm ${item.id === selectedId ? 'border-red-300 bg-red-50' : 'border-slate-200'}`}><b>{item.projectName}</b><span className="mt-1 block text-slate-500">{statusLabels[item.status]} · {item.riskLevel}风险 · 损失{item.estimatedLoss ?? '待补充'}</span>{item.overdue && <span className="mt-1 block text-red-600">已超期</span>}</button>)}{!todos.length && <p className="text-sm text-slate-500">暂无待办</p>}</div></aside>
      {selected && <section className="app-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">{selected.projectName}</h3><p className="text-sm text-slate-500">{selected.block} · {selected.owner}</p></div><span className="rounded bg-slate-100 px-2 py-1 text-sm">{statusLabels[selected.status]}</span></div>
        {canEdit && <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); void save({ status: data.get('status'), governanceMeasure: data.get('governanceMeasure'), owner: data.get('owner'), plannedDate: data.get('plannedDate') || null, actualDate: data.get('actualDate') || null, beforeMetric: data.get('beforeMetric') === '' ? null : Number(data.get('beforeMetric')), afterMetric: data.get('afterMetric') === '' ? null : Number(data.get('afterMetric')), riskLevel: data.get('riskLevel'), estimatedLoss: data.get('estimatedLoss') === '' ? null : Number(data.get('estimatedLoss')), affectedWellCount: data.get('affectedWellCount') === '' ? null : Number(data.get('affectedWellCount')), closureEvidence: data.get('closureEvidence') }); }}><label>项目状态<select name="status" className="field-control" defaultValue={selected.status}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>责任人<input name="owner" className="field-control" defaultValue={selected.owner}/></label><label className="md:col-span-2">治理措施<input name="governanceMeasure" className="field-control" defaultValue={selected.governanceMeasure} placeholder="例如：调剖封窜"/></label><label>计划日期<input name="plannedDate" type="date" className="field-control" defaultValue={selected.plannedDate ?? ''}/></label><label>实际日期<input name="actualDate" type="date" className="field-control" defaultValue={selected.actualDate ?? ''}/></label><label>治理前指标<input name="beforeMetric" type="number" min="0" className="field-control" defaultValue={selected.beforeMetric ?? ''}/></label><label>治理后指标<input name="afterMetric" type="number" min="0" className="field-control" defaultValue={selected.afterMetric ?? ''}/></label><label>风险等级<select name="riskLevel" className="field-control" defaultValue={selected.riskLevel}><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></label><label>预计损失<input name="estimatedLoss" type="number" min="0" className="field-control" defaultValue={selected.estimatedLoss ?? ''}/></label><label>影响井数<input name="affectedWellCount" type="number" min="0" step="1" className="field-control" defaultValue={selected.affectedWellCount ?? ''}/></label><label className="md:col-span-2">关闭依据（关闭时必填）<textarea name="closureEvidence" className="field-control" defaultValue={selected.closureEvidence}/></label><button className="action-button action-primary md:col-span-2">保存治理信息</button></form>}</section>}
    </section>
  </div>;
}
