import { useEffect, useMemo, useState } from 'react';
import type { ChannelingGovernanceStatus, ChannelingProject, ChannelingRelation, ChannelingRelationInput } from '../lib/channelingProjectStore';
import type { ChannelingRelationImport } from '../lib/channelingRelationImport';

const statusLabels: Record<ChannelingGovernanceStatus, string> = { identified: '识别/导入', confirmed: '确认', risk_assessed: '风险分级', planned: '治理方案', governing: '执行跟踪', verifying: '效果验证', closed: '关闭', recurred: '复发回流' };
const relationLabels = { confirmed: '已确认', suspected: '疑似', released: '已解除' } as const;
const today = () => new Date().toISOString().slice(0, 10);
const blankRelation = (): Omit<ChannelingRelationInput, 'projectId'> => ({ injectionWell: '', productionWell: '', reservoirLayer: '', impactLevel: 'medium', confidence: .5, status: 'confirmed', source: 'manual', evidence: '', effectiveStartDate: today(), effectiveEndDate: today(), owner: '' });
type Props = { role: string };

export function ChannelingProjectManagement({ role }: Props) {
  const isAdmin = role === 'admin';
  const canOperate = isAdmin || ['technical', 'technician', 'operation', 'operator'].includes(role);
  const [projects, setProjects] = useState<ChannelingProject[]>([]);
  const [todos, setTodos] = useState<(ChannelingProject & { overdue: boolean })[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [message, setMessage] = useState('');
  const [relations, setRelations] = useState<ChannelingRelation[]>([]);
  const [imports, setImports] = useState<ChannelingRelationImport[]>([]);
  const [relationDraft, setRelationDraft] = useState(blankRelation());
  const [newProject, setNewProject] = useState({ projectName: '', block: '', owner: '' });
  const [projectFilters, setProjectFilters] = useState({ block: '', status: '' });
  const [relationFilters, setRelationFilters] = useState({ status: '', source: '' });
  const selected = projects.find((item) => item.id === selectedId);
  const visibleProjects = useMemo(() => projects.filter((item) => (!projectFilters.block || item.block.includes(projectFilters.block)) && (!projectFilters.status || item.status === projectFilters.status)), [projects, projectFilters]);
  const visibleRelations = useMemo(() => relations.filter((item) => (!relationFilters.status || item.status === relationFilters.status) && (!relationFilters.source || item.source === relationFilters.source)), [relations, relationFilters]);
  const headers = { 'x-channeling-role': role };
  const load = async () => {
    const [projectResponse, todoResponse] = await Promise.all([fetch('/api/channeling-projects'), fetch(`/api/channeling-projects/pending?date=${today()}`)]);
    const [projectPayload, todoPayload] = await Promise.all([projectResponse.json(), todoResponse.json()]);
    if (projectPayload.success) { setProjects(projectPayload.data); setSelectedId((id) => id ?? projectPayload.data[0]?.id ?? null); }
    if (todoPayload.success) setTodos(todoPayload.data);
  };
  useEffect(() => { void load().catch(() => setMessage('项目加载失败')); }, []);
  const loadRelations = async (projectId: number) => {
    const [relationPayload, importPayload] = await Promise.all([fetch(`/api/channeling-projects/${projectId}/relations`).then((r) => r.json()), fetch(`/api/channeling-projects/${projectId}/relation-imports`).then((r) => r.json())]);
    if (relationPayload.success) setRelations(relationPayload.data);
    if (importPayload.success) setImports(importPayload.data);
  };
  useEffect(() => { if (selectedId) void loadRelations(selectedId).catch(() => setMessage('关系加载失败')); else { setRelations([]); setImports([]); } }, [selectedId]);
  const request = async (url: string, init: RequestInit) => {
    const response = await fetch(url, { ...init, headers: { ...headers, ...(init.headers || {}) } });
    const payload = await response.json();
    if (!response.ok || !payload.success) throw new Error(payload.message || '操作失败');
    return payload.data;
  };
  const save = async (changes: Record<string, unknown>) => { if (!selected) return; try { await request(`/api/channeling-projects/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); await load(); setMessage('治理台账已保存'); } catch (error: any) { setMessage(error.message); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await request('/api/channeling-projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newProject) }); setNewProject({ projectName: '', block: '', owner: '' }); await load(); setSelectedId(created.id); } catch (error: any) { setMessage(error.message); } };
  const createRelation = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; try { await request(`/api/channeling-projects/${selected.id}/relations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(relationDraft) }); setRelationDraft(blankRelation()); await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  const uploadRelations = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !selected) return; const body = new FormData(); body.append('file', file); try { await request(`/api/channeling-projects/${selected.id}/relation-imports/preview`, { method: 'POST', body }); await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  const confirmImport = async (id: number) => { try { await request(`/api/channeling-relation-imports/${id}/confirm`, { method: 'POST' }); if (selected) await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  const confirmSuspected = async (id: number) => { try { await request(`/api/channeling-relations/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'confirmed' }) }); if (selected) await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  const releaseRelation = async (id: number) => { try { await request(`/api/channeling-relations/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'released' }) }); if (selected) await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  const deleteProject = async () => { if (!selected || !window.confirm('删除后无法恢复，是否继续？')) return; try { await request(`/api/channeling-projects/${selected.id}`, { method: 'DELETE' }); setSelectedId(null); await load(); } catch (error: any) { setMessage(error.message); } };
  const deleteRelation = async (id: number) => { if (!window.confirm('删除关系后无法恢复，是否继续？')) return; try { await request(`/api/channeling-relations/${id}`, { method: 'DELETE' }); if (selected) await loadRelations(selected.id); } catch (error: any) { setMessage(error.message); } };
  return <div className="page-stack">
    <section className="app-card p-5"><h3 className="section-title">注窜项目台账（治理闭环）</h3><p className="mt-1 text-sm text-slate-500">所有角色均可查看完整项目、关系和筛选结果。</p>{message && <p className="status-banner status-banner-info mt-3">{message}</p>}
      {canOperate && <form className="mt-4 grid gap-2 md:grid-cols-4" onSubmit={create}><input className="field-control" required placeholder="项目名称" value={newProject.projectName} onChange={(e) => setNewProject({ ...newProject, projectName: e.target.value })}/><input className="field-control" required placeholder="区块" value={newProject.block} onChange={(e) => setNewProject({ ...newProject, block: e.target.value })}/><input className="field-control" required placeholder="责任人" value={newProject.owner} onChange={(e) => setNewProject({ ...newProject, owner: e.target.value })}/><button className="action-button action-primary">新增项目</button></form>}</section>
    <section className="grid gap-4 lg:grid-cols-[320px_1fr]"><aside className="app-card p-4"><h4 className="font-bold">完整项目清单</h4><div className="mt-3 grid gap-2"><input className="field-control" placeholder="按区块筛选" value={projectFilters.block} onChange={(e) => setProjectFilters({ ...projectFilters, block: e.target.value })}/><select className="field-control" aria-label="项目状态筛选" value={projectFilters.status} onChange={(e) => setProjectFilters({ ...projectFilters, status: e.target.value })}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="mt-3 space-y-2">{visibleProjects.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded border p-3 text-left text-sm ${item.id === selectedId ? 'border-red-300 bg-red-50' : 'border-slate-200'}`}><b>{item.projectName}</b><span className="mt-1 block text-slate-500">{item.block} ? {statusLabels[item.status]} ? {item.owner}</span></button>)}{!visibleProjects.length && <p className="text-sm text-slate-500">没有符合条件的项目{canOperate ? '，可新建项目或选择项目后导入关系。' : '。'}</p>}</div><h4 className="mt-6 font-bold">治理待办</h4><div className="mt-2 space-y-2">{todos.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className="w-full text-left text-sm text-slate-600">{item.projectName}{item.overdue ? ' ? 已超期' : ''}</button>)}{!todos.length && <p className="text-sm text-slate-500">暂无待办，但可通过上方清单查看全部台账。</p>}</div></aside>
      {selected ? <section className="app-card p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">{selected.projectName}</h3><p className="text-sm text-slate-500">{selected.block} ? {selected.owner}</p></div><div className="flex gap-2"><span className="rounded bg-slate-100 px-2 py-1 text-sm">{statusLabels[selected.status]}</span>{isAdmin && <button className="action-button" onClick={() => void deleteProject()}>删除项目</button>}</div></div>
        {canOperate && <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); void save({ owner: data.get('owner'), governanceMeasure: data.get('governanceMeasure'), plannedDate: data.get('plannedDate') || null, riskLevel: data.get('riskLevel'), ...(isAdmin ? { status: data.get('status'), closureEvidence: data.get('closureEvidence') } : {}) }); }}><label>项目状态<select name="status" className="field-control" defaultValue={selected.status} disabled={!isAdmin}>{Object.entries(statusLabels).filter(([value]) => isAdmin || value !== 'closed').map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>责任人<input name="owner" className="field-control" defaultValue={selected.owner}/></label><label className="md:col-span-2">治理措施<input name="governanceMeasure" className="field-control" defaultValue={selected.governanceMeasure}/></label><label>计划日期<input name="plannedDate" type="date" className="field-control" defaultValue={selected.plannedDate ?? ''}/></label><label>风险等级<select name="riskLevel" className="field-control" defaultValue={selected.riskLevel}><option value="high">高</option><option value="medium">中</option><option value="low">低</option></select></label>{isAdmin && <label className="md:col-span-2">关闭依据<input name="closureEvidence" className="field-control" defaultValue={selected.closureEvidence}/></label>}<button className="action-button action-primary md:col-span-2">保存治理信息</button></form>}
        <section className="mt-6 border-t pt-4"><h4 className="font-bold">关系清单</h4><div className="mt-3 grid gap-2 md:grid-cols-2"><select className="field-control" aria-label="关系状态筛选" value={relationFilters.status} onChange={(e) => setRelationFilters({ ...relationFilters, status: e.target.value })}><option value="">全部关系状态</option>{Object.entries(relationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select className="field-control" aria-label="关系来源筛选" value={relationFilters.source} onChange={(e) => setRelationFilters({ ...relationFilters, source: e.target.value })}><option value="">全部来源</option><option value="manual">手工</option><option value="import">导入</option><option value="suspected">疑似识别</option></select></div>
          {canOperate && <><form className="mt-3 grid gap-2 md:grid-cols-3" onSubmit={createRelation}><input className="field-control" required placeholder="注井" value={relationDraft.injectionWell} onChange={(e) => setRelationDraft({ ...relationDraft, injectionWell: e.target.value })}/><input className="field-control" required placeholder="采油井" value={relationDraft.productionWell} onChange={(e) => setRelationDraft({ ...relationDraft, productionWell: e.target.value })}/><input className="field-control" required placeholder="层系" value={relationDraft.reservoirLayer} onChange={(e) => setRelationDraft({ ...relationDraft, reservoirLayer: e.target.value })}/><input className="field-control" required placeholder="证据" value={relationDraft.evidence} onChange={(e) => setRelationDraft({ ...relationDraft, evidence: e.target.value })}/><input className="field-control" required placeholder="责任人" value={relationDraft.owner} onChange={(e) => setRelationDraft({ ...relationDraft, owner: e.target.value })}/><button className="action-button action-primary">手工新增关系</button></form><label className="mt-3 block text-sm">Excel关系预览与确认<input className="mt-1 block" type="file" accept=".xlsx,.xls" onChange={uploadRelations}/></label></>}
          <div className="mt-3 space-y-2">{visibleRelations.map((row) => <div key={row.id} className="flex flex-wrap items-center gap-3 text-sm"><span>{row.injectionWell} - {row.productionWell} - {row.reservoirLayer} ? {relationLabels[row.status]}</span>{canOperate && row.status === 'suspected' && <button onClick={() => void confirmSuspected(row.id)}>提交疑似确认</button>}{isAdmin && row.status !== 'released' && <button onClick={() => void releaseRelation(row.id)}>解除关系</button>}{isAdmin && <button onClick={() => void deleteRelation(row.id)}>删除关系</button>}</div>)}{!visibleRelations.length && <p className="text-sm text-slate-500">暂无符合条件的关系{canOperate ? '，可手工新增或导入 Excel 关系。' : '。'}</p>}</div><div className="mt-3">{imports.map((item) => <div key={item.id} className="flex gap-3 text-sm"><span>{item.fileName}：有效 {item.validCount}，无效 {item.invalidCount}</span>{canOperate && item.status === 'preview' && <button onClick={() => void confirmImport(item.id)}>确认导入</button>}</div>)}</div></section></section> : <section className="app-card p-5 text-sm text-slate-500">暂无项目详情。{canOperate ? '请新建项目，以便导入关系或提交疑似确认。' : '可使用左侧筛选查看完整台账。'}</section>}
    </section>
  </div>;
}
