import { useEffect, useMemo, useRef, useState } from 'react';
import * as XLSX from 'xlsx';

type Project = {
  id: number; projectNo: string; wellNo: string; block: string; processType: string; plannedTransferDate: string; owner: string;
  plannedSteam?: number | null; remark?: string; unit?: string | null; boiler?: string | null; plannedStartDate?: string | null;
  plannedEndDate?: string | null; gasSupport?: string | null; scheduleStatus?: string | null; sourceImportId?: number | null;
  planStatus: string; lifecycleStatus: string;
};
type ImportBatch = { id: number; planMonth: string; fileName: string; sheetName: string | null; status: string; validCount: number; pendingCount: number; invalidCount: number; totalPlannedSteam: number; createdAt: string; confirmedAt: string | null };
type PreviewRow = { unit: string; boiler: string; wellNo: string; plannedSteam: number | null; gasSupport: string; startDate: string | null; endDate: string | null; planStatus: string; remark: string; rowClass: '有效' | '待定' | '异常' };

const transitions: Record<string, string | undefined> = { pending: 'injecting', injecting: 'soaking', soaking: 'pendingTransfer', pendingTransfer: 'producing', producing: 'closed' };
const planStatusText: Record<string, string> = { draft: '草拟', issued: '已下达', cancelled: '已取消', closed: '已关闭' };
const lifecycleText: Record<string, string> = { pending: '待注汽', injecting: '注汽中', soaking: '焖井中', pendingTransfer: '待转抽', producing: '生产中', closed: '已关闭' };
const scheduleText: Record<string, string> = { scheduled: '已排期', stopped: '停注', superseded: '已替换', invalid: '异常' };
const importText: Record<string, string> = { preview: '待确认', confirmed: '已确认', superseded: '已替换' };
const pendingStatuses = ['停注检修', '待定', '停注', '先搬家', '接大一站'];

function cellText(value: unknown) { return value == null ? '' : String(value).trim(); }
function parseClientPreview(file: File): Promise<PreviewRow[]> {
  return file.arrayBuffer().then((buffer) => {
    const workbook = XLSX.read(buffer, { type: 'array' });
    const sheetName = workbook.SheetNames.find((name) => XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[name], { header: 1, defval: '' }).some((row) => row.some((value) => cellText(value).includes('注汽运行计划表'))));
    if (!sheetName) return [];
    const values = XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[sheetName], { header: 1, defval: '' });
    const titleIndex = values.findIndex((row) => row.some((value) => cellText(value).includes('注汽运行计划表')));
    const year = Number((values[titleIndex] || []).map(cellText).join(' ').match(/(20\d{2})年/)?.[1] || new Date().getFullYear());
    let unit = ''; let boiler = ''; const rows: PreviewRow[] = [];
    for (let row = Math.max(titleIndex + 1, 0); row < values.length; row += 2) {
      const wells = values[row] || []; const schedules = values[row + 1] || [];
      if (wells.some((value) => cellText(value).includes('单位')) && wells.some((value) => /注汽(站|炉|锅炉)|正注井/.test(cellText(value)))) continue;
      if (cellText(wells[0])) unit = cellText(wells[0]);
      if (cellText(wells[1])) boiler = cellText(wells[1]);
      for (let col = 2; col < wells.length; col += 1) {
        const rawWell = cellText(wells[col]); const rawSchedule = cellText(schedules[col]);
        if (!rawWell) continue;
        const pending = pendingStatuses.find((status) => rawWell.includes(status));
        if (pending) { rows.push({ unit, boiler, wellNo: rawWell, plannedSteam: null, gasSupport: '', startDate: null, endDate: null, planStatus: pending, remark: rawSchedule, rowClass: '待定' }); continue; }
        const matched = rawWell.match(/^\s*(.+?)\s*[（(]\s*(.*?)\s*[）)]\s*$/);
        const parts = matched?.[2].split('+').map((part) => part.trim()).filter(Boolean) || [];
        const steam = Number(parts.at(-1));
        const dates = [...rawSchedule.matchAll(/(\d{1,2})\s*(?:\.|月)\s*(\d{1,2})(?:日)?/g)];
        const date = (index: number) => dates[index] ? `${year}-${dates[index][1].padStart(2, '0')}-${dates[index][2].padStart(2, '0')}` : null;
        const gas = parts.slice(0, -1).map((part) => part === 'N' ? 'N2' : part).join('+');
        const invalid = !matched || !Number.isFinite(steam) || steam <= 0 || dates.length < 2;
        rows.push({ unit, boiler, wellNo: matched?.[1].trim() || rawWell, plannedSteam: Number.isFinite(steam) && steam > 0 ? steam : null, gasSupport: gas, startDate: invalid ? null : date(0), endDate: invalid ? null : date(1), planStatus: rawSchedule.includes('停注') ? '停注' : invalid ? '异常' : '已排期', remark: invalid ? (matched ? '无法解析日期' : '无法解析井表达式') : rawSchedule, rowClass: rawSchedule.includes('停注') ? '待定' : invalid ? '异常' : '有效' });
      }
    }
    return rows;
  });
}

export function InjectionProjectManagement() {
  const [projects, setProjects] = useState<Project[]>([]); const [imports, setImports] = useState<ImportBatch[]>([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' });
  const [preview, setPreview] = useState<ImportBatch | null>(null); const [previewRows, setPreviewRows] = useState<PreviewRow[]>([]); const [uploading, setUploading] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [filters, setFilters] = useState({ unit: '', boiler: '', planStatus: '', lifecycleStatus: '' });
  const load = () => Promise.all([
    fetch('/api/injection-projects').then((r) => r.json()), fetch('/api/injection-project-imports').then((r) => r.json()),
  ]).then(([projectPayload, importPayload]) => { if (!projectPayload.success) throw new Error(projectPayload.message); if (!importPayload.success) throw new Error(importPayload.message); setProjects(projectPayload.data); setImports(importPayload.data); }).catch((cause) => setError(cause.message || '项目加载失败'));
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/injection-projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } setForm({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' }); void load(); };
  const action = async (project: Project, endpoint: string, body: Record<string, string>) => { const response = await fetch(`/api/injection-projects/${project.id}/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } void load(); };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(''); setUploading(true); try { const rows = await parseClientPreview(file); const data = new FormData(); data.append('file', file); const response = await fetch('/api/injection-project-imports/preview', { method: 'POST', body: data }); const payload = await response.json(); if (!payload.success) throw new Error(payload.message); setPreview(payload.data); setPreviewRows(rows); void load(); } catch (cause: any) { setError(cause.message || '计划表解析失败'); } finally { setUploading(false); event.target.value = ''; } };
  const confirmPreview = async () => { if (!preview || !window.confirm(`确认以 ${preview.fileName} 覆盖 ${preview.planMonth} 的月度计划？`)) return; const response = await fetch(`/api/injection-project-imports/${preview.id}/confirm`, { method: 'POST' }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } setPreview({ ...preview, ...payload.data }); void load(); };
  const filteredProjects = useMemo(() => projects.filter((project) => (!filters.unit || project.unit === filters.unit) && (!filters.boiler || project.boiler === filters.boiler) && (!filters.planStatus || project.planStatus === filters.planStatus) && (!filters.lifecycleStatus || project.lifecycleStatus === filters.lifecycleStatus)), [projects, filters]);
  const timelineGroups = useMemo(() => Object.entries(filteredProjects.filter((project) => project.boiler && project.plannedStartDate && project.plannedEndDate).reduce<Record<string, Project[]>>((result, project) => { (result[project.boiler!] ||= []).push(project); return result; }, {})), [filteredProjects]);
  const options = (key: 'unit' | 'boiler' | 'planStatus' | 'lifecycleStatus') => [...new Set(projects.map((project) => project[key]).filter(Boolean))] as string[];
  const previewCounts = previewRows.reduce((result, row) => { result[row.rowClass] += 1; return result; }, { 有效: 0, 待定: 0, 异常: 0 });

  return <div className="page-stack">
    <section className="app-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">月度注汽计划导入</h3><p className="mt-1 text-sm text-slate-500">上传主计划表，解析预览后确认覆盖同月计划。</p></div><input ref={inputRef} className="hidden" type="file" accept=".xlsx,.xls" onChange={upload} /><button className="action-button action-primary" disabled={uploading} onClick={() => inputRef.current?.click()}>{uploading ? '解析中…' : '选择 .xlsx / .xls 文件'}</button></div>
      {preview && <div className="mt-4 rounded-lg border border-violet-200 bg-violet-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{preview.planMonth} · {preview.fileName}</p><p className="mt-1 text-sm text-slate-600">工作表：{preview.sheetName || '--'}　总计划量：{preview.totalPlannedSteam}</p></div><button className="action-button action-primary" disabled={preview.status !== 'preview'} onClick={confirmPreview}>{preview.status === 'preview' ? '确认覆盖并生成项目' : importText[preview.status] || preview.status}</button></div><div className="mt-3 grid grid-cols-4 gap-2 text-center text-sm"><div className="rounded bg-white p-2">有效<br /><b>{preview.validCount || previewCounts.有效}</b></div><div className="rounded bg-white p-2">待定<br /><b>{preview.pendingCount || previewCounts.待定}</b></div><div className="rounded bg-white p-2">异常<br /><b>{preview.invalidCount || previewCounts.异常}</b></div><div className="rounded bg-white p-2">总量<br /><b>{preview.validCount + preview.pendingCount + preview.invalidCount}</b></div></div>
        <div className="mt-3 max-h-64 overflow-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white text-xs text-slate-500"><tr>{['单位', '锅炉', '井', '开/停计划', '量', '气体', '状态', '备注'].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody className="divide-y divide-violet-100">{previewRows.map((row, index) => <tr key={`${row.wellNo}-${index}`}><td className="px-2 py-2">{row.unit || '--'}</td><td className="px-2 py-2">{row.boiler || '--'}</td><td className="px-2 py-2">{row.wellNo}</td><td className="px-2 py-2">{row.startDate && row.endDate ? `${row.startDate} 至 ${row.endDate}` : '无日期'}</td><td className="px-2 py-2">{row.plannedSteam ?? '--'}</td><td className="px-2 py-2">{row.gasSupport || '--'}</td><td className="px-2 py-2">{row.planStatus}</td><td className="px-2 py-2">{row.remark || '--'}</td></tr>)}{previewRows.length === 0 && <tr><td colSpan={8} className="px-2 py-4 text-slate-500">本地未读取到明细；服务端仍已完成导入预览。</td></tr>}</tbody></table></div></div>}
      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section>
    <section className="app-card overflow-hidden"><div className="app-card-header"><h3 className="font-bold">导入历史</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['月份', '文件', '工作表', '有效/待定/异常', '计划量', '状态', '确认时间'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{imports.map((item) => <tr key={item.id}><td className="px-3 py-3">{item.planMonth}</td><td className="px-3 py-3">{item.fileName}</td><td className="px-3 py-3">{item.sheetName || '--'}</td><td className="px-3 py-3">{item.validCount} / {item.pendingCount} / {item.invalidCount}</td><td className="px-3 py-3">{item.totalPlannedSteam}</td><td className="px-3 py-3">{importText[item.status] || item.status}</td><td className="px-3 py-3">{item.confirmedAt ? item.confirmedAt.slice(0, 16).replace('T', ' ') : '--'}</td></tr>)}{imports.length === 0 && <tr><td colSpan={7} className="px-3 py-5 text-slate-500">暂无导入记录。</td></tr>}</tbody></table></div></section>
    <section className="app-card p-5"><h3 className="text-lg font-bold">新建注汽方案</h3><form className="mt-4 grid gap-3 md:grid-cols-5" onSubmit={create}>{(['wellNo', 'block', 'processType', 'plannedTransferDate', 'owner'] as const).map((field) => <input key={field} className="field-control" required type={field === 'plannedTransferDate' ? 'date' : 'text'} placeholder={{ wellNo: '井号', block: '区块', processType: '注汽工艺', plannedTransferDate: '计划转抽日', owner: '负责人' }[field]} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} />)}<button className="action-button action-primary md:col-span-5">创建草拟方案</button></form></section>
    <section className="app-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">项目筛选</h3><div className="grid gap-2 sm:grid-cols-4">{(['unit', 'boiler', 'planStatus', 'lifecycleStatus'] as const).map((key) => <select key={key} className="field-control" value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })}><option value="">全部{key === 'unit' ? '单位' : key === 'boiler' ? '锅炉' : key === 'planStatus' ? '计划状态' : '生命周期'}</option>{options(key).map((value) => <option key={value} value={value}>{key === 'planStatus' ? planStatusText[value] || value : key === 'lifecycleStatus' ? lifecycleText[value] || value : value}</option>)}</select>)}</div></div></section>
    <section className="app-card overflow-hidden"><div className="app-card-header"><h3 className="font-bold">注汽项目（{filteredProjects.length}）</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['方案编号', '单位', '锅炉', '井号', '计划开/停', '计划量', '气体', '计划状态', '生命周期', '来源批次', '操作'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filteredProjects.map((project) => <tr key={project.id}><td className="px-3 py-3">{project.projectNo}</td><td className="px-3 py-3">{project.unit || '--'}</td><td className="px-3 py-3">{project.boiler || '--'}</td><td className="px-3 py-3">{project.wellNo}</td><td className="px-3 py-3">{project.plannedStartDate && project.plannedEndDate ? `${project.plannedStartDate} 至 ${project.plannedEndDate}` : project.scheduleStatus ? scheduleText[project.scheduleStatus] || project.scheduleStatus : '--'}</td><td className="px-3 py-3">{project.plannedSteam ?? '--'}</td><td className="px-3 py-3">{project.gasSupport || '--'}</td><td className="px-3 py-3">{planStatusText[project.planStatus] || project.planStatus}</td><td className="px-3 py-3">{lifecycleText[project.lifecycleStatus] || project.lifecycleStatus}</td><td className="px-3 py-3">{project.sourceImportId ? `批次 #${project.sourceImportId}` : '手工'}</td><td className="space-x-2 px-3 py-3">{project.planStatus === 'draft' && <button className="text-violet-700" onClick={() => action(project, 'plan-status', { status: 'issued' })}>下达</button>}{transitions[project.lifecycleStatus] && <button className="text-violet-700" onClick={() => action(project, 'transitions', { status: transitions[project.lifecycleStatus]!, actualDate: new Date().toISOString().slice(0, 10) })}>进入{lifecycleText[transitions[project.lifecycleStatus]!]}</button>}</td></tr>)}{filteredProjects.length === 0 && <tr><td colSpan={11} className="px-3 py-5 text-slate-500">没有符合筛选条件的项目。</td></tr>}</tbody></table></div></section>
    <section className="app-card p-5"><h3 className="font-bold">锅炉计划时间轴</h3><p className="mt-1 text-sm text-slate-500">仅展示开、停日期完整的计划；无日期记录显示为待定或异常。</p><div className="mt-4 space-y-4">{timelineGroups.map(([boiler, items]) => <div key={boiler}><p className="mb-2 text-sm font-medium">{boiler}</p><div className="space-y-2">{items.map((project) => <div key={project.id} className="flex flex-wrap items-center gap-3 rounded bg-slate-50 px-3 py-2 text-sm"><b className="w-20">{project.wellNo}</b><span>{project.plannedStartDate} → {project.plannedEndDate}</span><span className="text-slate-500">计划量 {project.plannedSteam ?? '--'} · {project.gasSupport || '无气体信息'}</span></div>)}</div></div>)}{timelineGroups.length === 0 && <p className="text-sm text-slate-500">暂无日期完整的锅炉计划。</p>}{filteredProjects.filter((project) => project.sourceImportId && (!project.plannedStartDate || !project.plannedEndDate)).length > 0 && <p className="rounded bg-amber-50 p-3 text-sm text-amber-800">待定/异常：{filteredProjects.filter((project) => project.sourceImportId && (!project.plannedStartDate || !project.plannedEndDate)).map((project) => `${project.wellNo}（${scheduleText[project.scheduleStatus || ''] || '无日期'}）`).join('、')}</p>}</div></section>
  </div>;
}
