import { useEffect, useMemo, useRef, useState } from 'react';
import ReactECharts from 'echarts-for-react';
import { formatShanghaiBusinessDate } from '../lib/businessDate';
import { filterProjectsByInitialId } from '../lib/injectionStatusMapNavigation';
import { buildConstructionDashboard, buildSoakTransferDashboard, filterComparisonForView, filterProjectsForView, isOverdue, summarizeComparisonForView, type InjectionProjectView } from '../lib/injectionProjectViews';

type Project = {
  id: number; projectNo: string; wellNo: string; block: string; processType: string; plannedTransferDate: string; owner: string;
  plannedSteam?: number | null; remark?: string; unit?: string | null; boiler?: string | null; plannedStartDate?: string | null;
  plannedEndDate?: string | null; gasSupport?: string | null; scheduleStatus?: string | null; sourceImportId?: number | null; soakStartDate?: string | null;
  planStatus: string; lifecycleStatus: string;
};
type ImportBatch = { id: number; planMonth: string; fileName: string; sheetName: string | null; status: string; validCount: number; pendingCount: number; invalidCount: number; totalPlannedSteam: number; createdAt: string; confirmedAt: string | null; previousComparison?: { added: number; modified: number; removed: number } | null };
type PreviewRow = { unit: string | null; boiler: string | null; wellNo: string | null; plannedSteam: number | null; gasSupport: string | null; startDate: string | null; endDate: string | null; planStatus: string | null; remark: string | null; };
type ComparisonStatus = 'not_started' | 'in_progress' | 'on_schedule' | 'early' | 'delayed' | 'incomplete' | 'suspected_other_cycle';
type PlanActualComparison = { projectId: number; planMonth: string | null; wellNo: string; plannedStartDate: string | null; actualStartDate: string | null; startVarianceDays: number | null; plannedEndDate: string | null; actualEndDate: string | null; endVarianceDays: number | null; plannedBoiler: string | null; actualBoiler: string | null; boilerMatches: boolean | null; plannedSteam: number | null; actualSteam: number | null; steamVariance: number | null; completionRate: number | null; plannedProcess: string | null; actualProcess: string | null; comparisonStatus: ComparisonStatus; };
type ComparisonResult = { rows: PlanActualComparison[]; summary: { planned: number; executed: number; onSchedule: number; early: number; delayed: number; notStarted: number; suspectedOtherCycle: number }; charts: { startVarianceBuckets: { label: string; count: number }[]; endVarianceBuckets: { label: string; count: number }[]; boilerSteamTotals: { boiler: string; plannedSteam: number; actualSteam: number }[] }; };

const transitions: Record<string, string | undefined> = { pending: 'injecting', injecting: 'soaking', soaking: 'pendingTransfer', pendingTransfer: 'producing', producing: 'closed' };
const planStatusText: Record<string, string> = { draft: '草拟', issued: '已下达', cancelled: '已取消', closed: '已关闭' };
const lifecycleText: Record<string, string> = { pending: '待注汽', injecting: '注汽中', soaking: '焖井中', pendingTransfer: '待转抽', producing: '生产中', closed: '已关闭' };
const scheduleText: Record<string, string> = { scheduled: '已排期', stopped: '停注', superseded: '已替换', invalid: '异常' };
const importText: Record<string, string> = { preview: '待确认', confirmed: '已确认', superseded: '已替换' };
const comparisonStatusText: Record<ComparisonStatus, string> = { not_started: '\u672a\u6267\u884c', in_progress: '\u6267\u884c\u4e2d', on_schedule: '\u6309\u8ba1\u5212', early: '\u63d0\u524d', delayed: '\u6ede\u540e', incomplete: '\u6570\u636e\u4e0d\u5b8c\u6574', suspected_other_cycle: '\u7591\u4f3c\u975e\u672c\u8f6e' };
const deviationStatuses = new Set<ComparisonStatus>(['early', 'delayed', 'not_started', 'suspected_other_cycle']);

export function getInjectionDashboardRenderMode(view: InjectionProjectView) {
  return {
    planExecution: view === 'plan',
    planComparison: view === 'plan',
    planTimeline: view === 'plan',
    construction: view === 'construction',
    soakTransfer: view === 'soakTransfer',
  };
}
export function InjectionProjectManagement({ view = 'plan', initialProjectId, onClearProjectLocation, onClearInitialProjectId }: { view?: InjectionProjectView; initialProjectId?: string; onClearProjectLocation?: () => void; onClearInitialProjectId?: () => void }) {
  const dashboardMode = getInjectionDashboardRenderMode(view);
  const isPlan = dashboardMode.planExecution;
  const isConstruction = dashboardMode.construction;
  const isSoakTransfer = dashboardMode.soakTransfer;
  const viewTitle = isPlan ? '\u65b9\u6848\u4e0e\u8ba1\u5212' : isConstruction ? '\u65bd\u5de5\u76d1\u63a7' : '\u7116\u4e95\u8f6c\u62bd';
  const clearProjectLocation = onClearProjectLocation || onClearInitialProjectId;
  const [projects, setProjects] = useState<Project[]>([]); const [imports, setImports] = useState<ImportBatch[]>([]); const [comparisonResult, setComparisonResult] = useState<ComparisonResult | null>(null); const [comparisonView, setComparisonView] = useState<'deviation' | 'all'>('deviation'); const [error, setError] = useState('');
  const [form, setForm] = useState({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' });
  const [preview, setPreview] = useState<ImportBatch | null>(null); const [previewRows, setPreviewRows] = useState<PreviewRow[]>([]); const [uploading, setUploading] = useState(false); const [importHistoryExpanded, setImportHistoryExpanded] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [filters, setFilters] = useState({ planMonth: '', unit: '', boiler: '', planStatus: '', lifecycleStatus: '', comparisonStatus: '' });
  const [projectLocationId, setProjectLocationId] = useState(initialProjectId);
  useEffect(() => { setProjectLocationId(initialProjectId); }, [initialProjectId]);
  const load = () => Promise.all([
    fetch('/api/injection-projects').then((r) => r.json()), fetch('/api/injection-project-imports').then((r) => r.json()),
    fetch(`/api/injection-projects/plan-actual-comparison?${new URLSearchParams(Object.entries({ planMonth: filters.planMonth, unit: filters.unit, boiler: filters.boiler, status: filters.comparisonStatus }).filter(([, value]) => value) as [string, string][]).toString()}`).then((r) => r.json()),
  ]).then(([projectPayload, importPayload, comparisonPayload]) => { if (!projectPayload.success) throw new Error(projectPayload.message); if (!importPayload.success) throw new Error(importPayload.message); if (!comparisonPayload.success) throw new Error(comparisonPayload.message); setProjects(projectPayload.data); setImports(importPayload.data); setComparisonResult(comparisonPayload.data); }).catch((cause) => setError(cause.message || '项目加载失败'));
  useEffect(() => { void load(); }, [filters]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/injection-projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } setForm({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' }); void load(); };
  const action = async (project: Project, endpoint: string, body: Record<string, string>) => { const response = await fetch(`/api/injection-projects/${project.id}/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } void load(); };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(''); setUploading(true); try { const data = new FormData(); data.append('file', file); const response = await fetch('/api/injection-project-imports/preview', { method: 'POST', body: data }); const payload = await response.json(); if (!payload.success) throw new Error(payload.message); setPreview(payload.data); setPreviewRows([...(payload.data.rows || []), ...(payload.data.pendingRows || []), ...(payload.data.invalidRows || [])]); void load(); } catch (cause: any) { setError(cause.message || '计划表解析失败'); } finally { setUploading(false); event.target.value = ''; } };
  const confirmPreview = async () => { if (!preview || !window.confirm(`确认以 ${preview.fileName} 覆盖 ${preview.planMonth} 的月度计划？`)) return; const response = await fetch(`/api/injection-project-imports/${preview.id}/confirm`, { method: 'POST' }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } setPreview({ ...preview, ...payload.data }); void load(); };
  const businessToday = formatShanghaiBusinessDate(new Date());
  const viewProjects = useMemo(() => filterProjectsForView(projects, view, businessToday), [projects, view, businessToday]);
  const hasInitialProjectOutsideView = Boolean(projectLocationId && projects.some((project) => String(project.id) === projectLocationId) && !viewProjects.some((project) => String(project.id) === projectLocationId));
  const filteredProjects = useMemo(() => filterProjectsByInitialId(viewProjects, projectLocationId).filter((project) => (!filters.unit || project.unit === filters.unit) && (!filters.boiler || project.boiler === filters.boiler) && (!filters.planStatus || project.planStatus === filters.planStatus) && (!filters.lifecycleStatus || project.lifecycleStatus === filters.lifecycleStatus)), [viewProjects, filters, projectLocationId]);
  const overdueProjects = useMemo(() => viewProjects.filter((project) => isOverdue(project, businessToday)), [viewProjects, businessToday]);
  const timelineGroups = useMemo(() => Object.entries(filteredProjects.filter((project) => project.boiler && project.plannedStartDate && project.plannedEndDate).reduce<Record<string, Project[]>>((result, project) => { (result[project.boiler!] ||= []).push(project); return result; }, {})), [filteredProjects]);
  const options = (key: 'unit' | 'boiler' | 'planStatus' | 'lifecycleStatus') => [...new Set(projects.map((project) => project[key]).filter(Boolean))] as string[];
  const comparisonDate = (start: string | null, end: string | null) => start || end ? `${start || '--'} 至 ${end || '--'}` : '--';
  const number = (value: number | null) => value == null ? '--' : value;
  const percent = (value: number | null) => value == null ? '--' : `${(value * 100).toFixed(1)}%`;
  const formatDateTime = (value: string | null) => value ? value.slice(0, 16).replace('T', ' ') : '--';
  const filteredComparisonRows = useMemo(() => filterComparisonForView(comparisonResult?.rows || [], filteredProjects), [comparisonResult, filteredProjects]);
  const viewComparisonResult = useMemo(() => summarizeComparisonForView(filteredComparisonRows), [filteredComparisonRows]);
  const comparisons = useMemo(() => filteredComparisonRows.filter((row) => comparisonView === 'all' || deviationStatuses.has(row.comparisonStatus)).sort((a, b) => Number(b.comparisonStatus === 'delayed') - Number(a.comparisonStatus === 'delayed') || a.wellNo.localeCompare(b.wellNo)), [comparisonView, filteredComparisonRows]);
  const constructionDashboard = useMemo(() => buildConstructionDashboard(filteredProjects, filteredComparisonRows, businessToday), [filteredProjects, filteredComparisonRows, businessToday]);
  const soakTransferDashboard = useMemo(() => buildSoakTransferDashboard(filteredProjects, businessToday), [filteredProjects, businessToday]);
  const chartOption = (title: string, labels: string[], series: Array<{ name: string; data: number[]; color: string }>) => ({
    title: { text: title, left: 'center', textStyle: { fontSize: 14 } }, tooltip: { trigger: 'axis' }, legend: series.length > 1 ? { bottom: 0 } : undefined,
    grid: { left: 36, right: 20, top: 48, bottom: series.length > 1 ? 38 : 28 }, xAxis: { type: 'category', data: labels, axisLabel: { interval: 0 } }, yAxis: { type: 'value', minInterval: 1 },
    series: series.map((item) => ({ name: item.name, type: 'bar', data: item.data, itemStyle: { color: item.color }, barMaxWidth: 38 })),
  });

  return <div className="page-stack">
    <section className="app-card p-5"><h3 className="text-xl font-bold">{viewTitle}</h3><p className="mt-1 text-sm text-slate-500">{isPlan ? '\u7edf\u4e00\u7ba1\u7406\u6ce8\u6c7d\u65b9\u6848\u3001\u8ba1\u5212\u548c\u6267\u884c\u8fdb\u5ea6\u3002' : isConstruction ? '\u805a\u7126\u5f85\u6ce8\u6c7d\u548c\u6ce8\u6c7d\u4e2d\u7684\u65bd\u5de5\u9879\u76ee\u3002' : '\u805a\u7126\u7116\u4e95\u4e0e\u5f85\u8f6c\u62bd\u9879\u76ee\uff0c\u903e\u671f\u5f85\u529e\u4f18\u5148\u3002'}</p></section>
    {isSoakTransfer && <section className="app-card border-l-4 border-l-red-500 p-5"><h3 className="font-bold text-red-700">{'\u903e\u671f\u5f85\u529e'}?{overdueProjects.length}?</h3><p className="mt-1 text-sm text-slate-600">{overdueProjects.length ? overdueProjects.map((project) => `${project.wellNo}?${project.plannedTransferDate}?`).join('?') : '\u6682\u65e0\u903e\u671f\u7116\u4e95\u6216\u5f85\u8f6c\u62bd\u9879\u76ee\u3002'}</p></section>}
    <section className={`app-card p-5 ${isPlan ? '' : 'hidden'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">月度注汽计划导入</h3><p className="mt-1 text-sm text-slate-500">上传主计划表，解析预览后确认覆盖同月计划。</p></div><input ref={inputRef} className="hidden" type="file" accept=".xlsx,.xls" onChange={upload} /><button className="action-button action-primary" disabled={uploading} onClick={() => inputRef.current?.click()}>{uploading ? '解析中…' : '选择 .xlsx / .xls 文件'}</button></div>
      {preview && <div className="mt-4 rounded-lg border border-violet-200 bg-violet-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{preview.planMonth} · {preview.fileName}</p><p className="mt-1 text-sm text-slate-600">工作表：{preview.sheetName || '--'}　计划注汽总量：{preview.totalPlannedSteam}</p></div><button className="action-button action-primary" disabled={preview.status !== 'preview'} onClick={confirmPreview}>{preview.status === 'preview' ? '确认覆盖并生成项目' : importText[preview.status] || preview.status}</button></div><div className="mt-3 grid grid-cols-5 gap-2 text-center text-sm"><div className="rounded bg-white p-2">有效<br /><b>{preview.validCount}</b></div><div className="rounded bg-white p-2">待定<br /><b>{preview.pendingCount}</b></div><div className="rounded bg-white p-2">异常<br /><b>{preview.invalidCount}</b></div><div className="rounded bg-white p-2">合计<br /><b>{preview.validCount + preview.pendingCount + preview.invalidCount}</b></div><div className="rounded bg-white p-2">计划注汽总量<br /><b>{preview.totalPlannedSteam}</b></div></div>
        {preview.previousComparison && <p className="mt-3 rounded bg-white px-3 py-2 text-sm text-slate-700">与同月上一确认版本对比：新增 {preview.previousComparison.added} 口，修改 {preview.previousComparison.modified} 口，移除 {preview.previousComparison.removed} 口。</p>}
        <div className="mt-3 max-h-64 overflow-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white text-xs text-slate-500"><tr>{['单位', '锅炉', '井', '开/停计划', '量', '气体', '状态', '备注'].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody className="divide-y divide-violet-100">{previewRows.map((row, index) => <tr key={`${row.wellNo}-${index}`}><td className="px-2 py-2">{row.unit || '--'}</td><td className="px-2 py-2">{row.boiler || '--'}</td><td className="px-2 py-2">{row.wellNo}</td><td className="px-2 py-2">{row.startDate && row.endDate ? `${row.startDate} 至 ${row.endDate}` : '无日期'}</td><td className="px-2 py-2">{row.plannedSteam ?? '--'}</td><td className="px-2 py-2">{row.gasSupport || '--'}</td><td className="px-2 py-2">{row.planStatus}</td><td className="px-2 py-2">{row.remark || '--'}</td></tr>)}{previewRows.length === 0 && <tr><td colSpan={8} className="px-2 py-4 text-slate-500">服务端未返回可展示的解析明细。</td></tr>}</tbody></table></div></div>}
      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section>
    <section className={`app-card overflow-hidden ${isPlan ? '' : 'hidden'}`}><div className="app-card-header flex items-center justify-between gap-3"><h3 className="font-bold">导入历史（{imports.length}）</h3><button className="text-sm font-medium text-violet-700" type="button" aria-expanded={importHistoryExpanded} onClick={() => setImportHistoryExpanded((expanded) => !expanded)}>{importHistoryExpanded ? '收起' : '展开'}</button></div>{importHistoryExpanded && <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['月份', '文件', '工作表', '有效/待定/异常', '计划量', '状态', '导入时间', '确认时间'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{imports.map((item) => <tr key={item.id}><td className="px-3 py-3">{item.planMonth}</td><td className="px-3 py-3">{item.fileName}</td><td className="px-3 py-3">{item.sheetName || '--'}</td><td className="px-3 py-3">{item.validCount} / {item.pendingCount} / {item.invalidCount}</td><td className="px-3 py-3">{item.totalPlannedSteam}</td><td className="px-3 py-3">{importText[item.status] || item.status}</td><td className="px-3 py-3">{formatDateTime(item.createdAt)}</td><td className="px-3 py-3">{formatDateTime(item.confirmedAt)}</td></tr>)}{imports.length === 0 && <tr><td colSpan={8} className="px-3 py-5 text-slate-500">暂无导入记录。</td></tr>}</tbody></table></div>}</section>
    <section className={`app-card p-5 ${isPlan ? '' : 'hidden'}`}><h3 className="text-lg font-bold">手工新增注汽计划</h3><form className="mt-4 grid gap-3 md:grid-cols-5" onSubmit={create}>{(['wellNo', 'block', 'processType', 'plannedTransferDate', 'owner'] as const).map((field) => <input key={field} className="field-control" required type={field === 'plannedTransferDate' ? 'date' : 'text'} placeholder={{ wellNo: '井号', block: '区块', processType: '注汽工艺', plannedTransferDate: '计划转抽日', owner: '负责人' }[field]} value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} />)}<button className="action-button action-primary md:col-span-5">创建草拟方案</button></form></section>
    <section className="app-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><h3 className="font-bold">{viewTitle}项目筛选</h3>{projectLocationId && <><span className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">地图定位项目 #{projectLocationId}</span><button type="button" className="text-sm text-blue-700" onClick={() => { setProjectLocationId(undefined); clearProjectLocation?.(); }}>清除</button></>}{hasInitialProjectOutsideView && <span className="rounded bg-amber-50 px-2 py-1 text-xs text-amber-800">{'\u9879\u76ee\u4e0d\u5c5e\u4e8e\u5f53\u524d\u4e1a\u52a1\u89c6\u56fe'}</span>}</div><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><select className="field-control" value={filters.planMonth} onChange={(event) => setFilters({ ...filters, planMonth: event.target.value })}><option value="">全部计划月份</option>{[...new Set(imports.map((item) => item.planMonth))].map((value) => <option key={value} value={value}>{value}</option>)}</select>{(['unit', 'boiler', 'planStatus', 'lifecycleStatus'] as const).map((key) => <select key={key} className="field-control" value={filters[key]} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })}><option value="">全部{key === 'unit' ? '单位' : key === 'boiler' ? '锅炉' : key === 'planStatus' ? '计划状态' : '生命周期'}</option>{options(key).map((value) => <option key={value} value={value}>{key === 'planStatus' ? planStatusText[value] || value : key === 'lifecycleStatus' ? lifecycleText[value] || value : value}</option>)}</select>)}<select className="field-control" value={filters.comparisonStatus} onChange={(event) => setFilters({ ...filters, comparisonStatus: event.target.value })}><option value="">全部偏差状态</option>{Object.entries(comparisonStatusText).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div></section>
    <section className={`app-card p-5 ${isPlan ? '' : 'hidden'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">{'\u8ba1\u5212\u6267\u884c\u7edf\u8ba1\u770b\u677f'}</h3><p className="mt-1 text-sm text-slate-500">{'\u7edf\u8ba1\u4e0e\u56fe\u8868\u968f\u4e0a\u65b9\u7b5b\u9009\u6761\u4ef6\u540c\u6b65\u66f4\u65b0\u3002'}</p></div><div className="rounded-lg bg-slate-100 p-1 text-sm"><button className={`rounded px-3 py-1.5 ${comparisonView === 'deviation' ? 'bg-white font-medium shadow-sm' : 'text-slate-600'}`} onClick={() => setComparisonView('deviation')}>{'\u4ec5\u504f\u5dee'}</button><button className={`rounded px-3 py-1.5 ${comparisonView === 'all' ? 'bg-white font-medium shadow-sm' : 'text-slate-600'}`} onClick={() => setComparisonView('all')}>{'\u5168\u90e8'}</button></div></div>
      <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{[['\u8ba1\u5212\u4e95\u6570', viewComparisonResult.summary.planned ?? 0, 'text-slate-900'], ['\u5df2\u6267\u884c', viewComparisonResult.summary.executed ?? 0, 'text-blue-700'], ['\u6309\u8ba1\u5212', viewComparisonResult.summary.onSchedule ?? 0, 'text-emerald-700'], ['\u63d0\u524d', viewComparisonResult.summary.early ?? 0, 'text-cyan-700'], ['\u6ede\u540e', viewComparisonResult.summary.delayed ?? 0, 'text-red-700'], ['\u672a\u6267\u884c', viewComparisonResult.summary.notStarted ?? 0, 'text-amber-700'], ['\u7591\u4f3c\u975e\u672c\u8f6e', viewComparisonResult.summary.suspectedOtherCycle ?? 0, 'text-slate-600']].map(([label, value, tone]) => <div key={label as string} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p></div>)}</div>
      <div className="mt-5 grid gap-4 xl:grid-cols-3"><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u5f00\u6ce8\u504f\u5dee\u5206\u5e03', (viewComparisonResult.charts.startVarianceBuckets || []).map((item) => item.label), [{ name: '\u4e95\u6570', data: (viewComparisonResult.charts.startVarianceBuckets || []).map((item) => item.count), color: '#2563eb' }])} /></div><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u505c\u6ce8\u504f\u5dee\u5206\u5e03', (viewComparisonResult.charts.endVarianceBuckets || []).map((item) => item.label), [{ name: '\u4e95\u6570', data: (viewComparisonResult.charts.endVarianceBuckets || []).map((item) => item.count), color: '#7c3aed' }])} /></div><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u9505\u7089\u8ba1\u5212 / \u5b9e\u9645\u6ce8\u6c7d\u91cf', (viewComparisonResult.charts.boilerSteamTotals || []).map((item) => item.boiler), [{ name: '\u8ba1\u5212\u6ce8\u6c7d\u91cf', data: (viewComparisonResult.charts.boilerSteamTotals || []).map((item) => item.plannedSteam), color: '#0ea5e9' }, { name: '\u5b9e\u9645\u6ce8\u6c7d\u91cf', data: (viewComparisonResult.charts.boilerSteamTotals || []).map((item) => item.actualSteam), color: '#22c55e' }])} /></div></div>
    </section>
    <section className={`app-card p-5 ${isConstruction ? '' : 'hidden'}`}><h3 className="text-lg font-bold">{'\u65bd\u5de5\u76d1\u63a7\u770b\u677f'}</h3><p className="mt-1 text-sm text-slate-500">{'\u6240\u6709\u6307\u6807\u548c\u56fe\u8868\u968f\u4e0a\u65b9\u7b5b\u9009\u540c\u6b65\u66f4\u65b0\u3002\u5f53\u65e5\u6ce8\u6c7d\u91cf\u6682\u65e0\u53ef\u9760\u751f\u4ea7\u6570\u636e\u3002'}</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[['\u65bd\u5de5\u4e2d\u4e95\u6570', constructionDashboard.kpis.active], ['\u7d2f\u8ba1\u5b9e\u9645\u6ce8\u6c7d\u91cf', constructionDashboard.kpis.cumulativeSteam], ['\u5f53\u65e5\u6ce8\u6c7d\u91cf', '\u6570\u636e\u5f85\u8865\u5168'], ['\u8fdb\u5ea6\u6ede\u540e', constructionDashboard.kpis.delayed], ['\u6570\u636e\u5f85\u8865\u5168', constructionDashboard.kpis.missingData]].map(([label, value]) => <div key={label as string} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u6309\u9505\u7089\u8ba1\u5212 / \u7d2f\u8ba1\u5b9e\u9645\u6ce8\u6c7d\u91cf', constructionDashboard.boilerSteamTotals.map((item) => item.boiler), [{ name: '\u8ba1\u5212\u6ce8\u6c7d\u91cf', data: constructionDashboard.boilerSteamTotals.map((item) => item.plannedSteam), color: '#0ea5e9' }, { name: '\u7d2f\u8ba1\u5b9e\u9645\u6ce8\u6c7d\u91cf', data: constructionDashboard.boilerSteamTotals.map((item) => item.actualSteam), color: '#22c55e' }])} /></div><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u5f85\u6ce8\u6c7d / \u6ce8\u6c7d\u4e2d\u5206\u5e03', constructionDashboard.statusDistribution.map((item) => lifecycleText[item.status] || item.status), [{ name: '\u4e95\u6570', data: constructionDashboard.statusDistribution.map((item) => item.count), color: '#6366f1' }])} /></div></div></section>
    <section className={`app-card overflow-hidden ${isConstruction ? '' : 'hidden'}`}><div className="app-card-header"><h3 className="font-bold">{'\u65bd\u5de5\u9879\u76ee\u6e05\u5355'}\uff08{constructionDashboard.projects.length}\uff09</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['\u4e95\u53f7', '\u8ba1\u5212\u91cf', '\u7d2f\u8ba1\u5b9e\u9645\u91cf', '\u5b8c\u6210\u7387', '\u5b9e\u9645\u9505\u7089', '\u5f02\u5e38\u72b6\u6001'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{constructionDashboard.projects.map((project) => { const row = constructionDashboard.rows.find((item) => item.projectId === project.id); return <tr key={project.id}><td className="px-3 py-3 font-medium">{project.wellNo}</td><td className="px-3 py-3">{number(row?.plannedSteam ?? project.plannedSteam ?? null)}</td><td className="px-3 py-3">{number(row?.actualSteam ?? null)}</td><td className="px-3 py-3">{percent(row?.completionRate ?? null)}</td><td className="px-3 py-3">{row?.actualBoiler || '--'}</td><td className="px-3 py-3">{row?.comparisonStatus === 'delayed' ? '\u8fdb\u5ea6\u6ede\u540e' : row?.comparisonStatus === 'incomplete' || !row ? '\u6570\u636e\u5f85\u8865\u5168' : '\u65e0'}</td></tr>; })}{constructionDashboard.projects.length === 0 && <tr><td colSpan={6} className="px-3 py-5 text-slate-500">{'\u6ca1\u6709\u7b26\u5408\u7b5b\u9009\u6761\u4ef6\u7684\u65bd\u5de5\u9879\u76ee\u3002'}</td></tr>}</tbody></table></div></section>
    <section className={`app-card p-5 ${isSoakTransfer ? '' : 'hidden'}`}><h3 className="text-lg font-bold">{'\u7116\u4e95\u8f6c\u62bd\u770b\u677f'}</h3><p className="mt-1 text-sm text-slate-500">{'\u6240\u6709\u6307\u6807\u548c\u56fe\u8868\u968f\u4e0a\u65b9\u7b5b\u9009\u540c\u6b65\u66f4\u65b0\u3002\u710a\u4e95\u8d77\u59cb\u65e5\u7f3a\u5931\u65f6\u6807\u6ce8\u4e3a\u6570\u636e\u5f85\u8865\u5168\u3002'}</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[['\u7116\u4e95\u4e2d', soakTransferDashboard.kpis.soaking], ['\u5f85\u8f6c\u62bd', soakTransferDashboard.kpis.pendingTransfer], ['\u8d85\u671f\u5f85\u529e', soakTransferDashboard.kpis.overdue], ['\u5e73\u5747\u7116\u4e95\u5929\u6570', soakTransferDashboard.kpis.averageSoakDays ?? '\u6570\u636e\u5f85\u8865\u5168'], ['\u8f6c\u62bd\u5b8c\u6210\u7387', '\u6570\u636e\u5f85\u8865\u5168']].map(([label, value]) => <div key={label as string} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u7116\u4e95\u65f6\u957f\u5206\u5e03', soakTransferDashboard.durationDistribution.map((item) => item.label), [{ name: '\u4e95\u6570', data: soakTransferDashboard.durationDistribution.map((item) => item.count), color: '#f59e0b' }])} /></div><div className="rounded-lg border border-slate-100"><ReactECharts style={{ height: 280 }} option={chartOption('\u8f6c\u62bd\u72b6\u6001\u5206\u5e03', soakTransferDashboard.statusDistribution.map((item) => lifecycleText[item.status] || item.status), [{ name: '\u4e95\u6570', data: soakTransferDashboard.statusDistribution.map((item) => item.count), color: '#8b5cf6' }])} /></div></div></section>
    <section className={`app-card overflow-hidden ${isSoakTransfer ? '' : 'hidden'}`}><div className="app-card-header"><h3 className="font-bold">{'\u8d85\u671f\u4f18\u5148\u5f85\u529e\u6e05\u5355'}\uff08{soakTransferDashboard.todo.length}\uff09</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['\u4e95\u53f7', '\u8ba1\u5212\u8f6c\u62bd\u65e5', '\u5f53\u524d\u9636\u6bb5', '\u7116\u4e95\u5929\u6570', '\u8d1f\u8d23\u4eba'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{soakTransferDashboard.todo.map((project) => { return <tr key={project.id} className={isOverdue(project, businessToday) ? 'bg-red-50 text-red-900' : ''}><td className="px-3 py-3 font-medium">{project.wellNo}</td><td className="px-3 py-3">{project.plannedTransferDate || '--'}</td><td className="px-3 py-3">{lifecycleText[project.lifecycleStatus] || project.lifecycleStatus}</td><td className="px-3 py-3">{project.soakDays ?? '\u6570\u636e\u5f85\u8865\u5168'}</td><td className="px-3 py-3">{project.owner || '--'}</td></tr>; })}{soakTransferDashboard.todo.length === 0 && <tr><td colSpan={5} className="px-3 py-5 text-slate-500">{'\u6ca1\u6709\u7b26\u5408\u7b5b\u9009\u6761\u4ef6\u7684\u7116\u4e95\u6216\u5f85\u8f6c\u62bd\u9879\u76ee\u3002'}</td></tr>}</tbody></table></div></section>
    <section className={`app-card p-5 ${isPlan ? '' : 'hidden'}`}><h3 className="font-bold">{'\u9505\u7089\u8ba1\u5212\u65f6\u95f4\u8f74'}</h3><p className="mt-1 text-sm text-slate-500">{'\u4ec5\u5c55\u793a\u5f00\u3001\u505c\u65e5\u671f\u5b8c\u6574\u7684\u8ba1\u5212\u3002'}</p><div className="mt-4 space-y-4">{timelineGroups.map(([boiler, items]) => { const day = 86400000; const starts = items.map((item) => Date.parse(item.plannedStartDate!)); const ends = items.map((item) => Date.parse(item.plannedEndDate!)); const earliest = Math.min(...starts); const latest = Math.max(...ends); const span = latest - earliest + day; return <div key={boiler}><p className="mb-2 text-sm font-medium">{boiler} <span className="font-normal text-slate-500">{new Date(earliest).toISOString().slice(0, 10)} {'\u81f3'} {new Date(latest).toISOString().slice(0, 10)}</span></p><div className="space-y-2">{items.map((project) => { const start = Date.parse(project.plannedStartDate!); const end = Date.parse(project.plannedEndDate!); return <div key={project.id} className="grid grid-cols-[5rem_minmax(0,1fr)] items-center gap-3 text-sm"><b>{project.wellNo}</b><div className="relative h-8 rounded bg-slate-50"><div className="absolute top-1 h-6 rounded bg-violet-600 px-2 leading-6 text-xs font-medium text-white" style={{ left: `${((start - earliest) / span) * 100}%`, width: `${((end - start + day) / span) * 100}%` }} title={`${project.plannedStartDate} \u81f3 ${project.plannedEndDate} \u00b7 \u8ba1\u5212\u91cf ${project.plannedSteam ?? '--'}`}>{project.wellNo}</div></div></div>; })}</div></div>; })}{timelineGroups.length === 0 && <p className="text-sm text-slate-500">{'\u6682\u65e0\u65e5\u671f\u5b8c\u6574\u7684\u9505\u7089\u8ba1\u5212\u3002'}</p>}{filteredProjects.filter((project) => project.sourceImportId && (!project.plannedStartDate || !project.plannedEndDate)).length > 0 && <p className="rounded bg-amber-50 p-3 text-sm text-amber-800">{'\u5f85\u5b9a/\u5f02\u5e38\uff1a'}{filteredProjects.filter((project) => project.sourceImportId && (!project.plannedStartDate || !project.plannedEndDate)).map((project) => `${project.wellNo}\uff08${scheduleText[project.scheduleStatus || ''] || '\u65e0\u65e5\u671f'}\uff09`).join('\u3001')}</p>}</div></section>
    <section className={`app-card overflow-hidden ${isPlan ? '' : 'hidden'}`}><div className="app-card-header"><h3 className="font-bold">{'\u8ba1\u5212\u6267\u884c\u5bf9\u6bd4'}\uff08{comparisons.length}\uff09</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1800px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['\u4e95\u53f7', '\u8ba1\u5212\u5f00/\u505c', '\u5b9e\u9645\u5f00/\u505c', '\u5f00/\u505c\u504f\u5dee\uff08\u5929\uff09', '\u8ba1\u5212\u9505\u7089', '\u5b9e\u9645\u9505\u7089', '\u8ba1\u5212\u6ce8\u6c7d\u91cf', '\u5b9e\u9645\u6ce8\u6c7d\u91cf', '\u6ce8\u6c7d\u91cf\u504f\u5dee', '\u5b8c\u6210\u7387', '\u8ba1\u5212\u5de5\u827a', '\u5b9e\u9645\u5de5\u827a', '\u72b6\u6001'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{comparisons.map((row) => <tr key={row.projectId} className={row.comparisonStatus === 'delayed' ? 'bg-red-50 text-red-900' : row.comparisonStatus === 'suspected_other_cycle' ? 'bg-slate-50 text-slate-600' : ''}><td className="px-3 py-3 font-medium">{row.wellNo}</td><td className="px-3 py-3">{comparisonDate(row.plannedStartDate, row.plannedEndDate)}</td><td className="px-3 py-3">{comparisonDate(row.actualStartDate, row.actualEndDate)}</td><td className="px-3 py-3">{'\u5f00'} {number(row.startVarianceDays)} / {'\u505c'} {number(row.endVarianceDays)}</td><td className="px-3 py-3">{row.plannedBoiler || '--'}</td><td className="px-3 py-3">{row.actualBoiler || '--'}{row.boilerMatches === false && <span className="ml-1 font-medium text-amber-700">{'\u4e0d\u4e00\u81f4'}</span>}</td><td className="px-3 py-3">{number(row.plannedSteam)}</td><td className="px-3 py-3">{number(row.actualSteam)}</td><td className="px-3 py-3">{number(row.steamVariance)}</td><td className="px-3 py-3">{percent(row.completionRate)}</td><td className="px-3 py-3">{row.plannedProcess || '--'}</td><td className="px-3 py-3">{row.actualProcess || '--'}</td><td className="px-3 py-3">{comparisonStatusText[row.comparisonStatus] || row.comparisonStatus}</td></tr>)}{comparisons.length === 0 && <tr><td colSpan={13} className="px-3 py-5 text-slate-500">{'\u6ca1\u6709\u7b26\u5408\u7b5b\u9009\u6761\u4ef6\u7684\u8ba1\u5212\u6267\u884c\u5bf9\u6bd4\u3002'}</td></tr>}</tbody></table></div></section>
        <section className={`app-card overflow-hidden ${isPlan ? '' : 'hidden'}`}><div className="app-card-header"><h3 className="font-bold">{viewTitle}注汽项目（{filteredProjects.length}）</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['方案编号', '单位', '锅炉', '井号', '计划开/停', '计划量', '气体', '计划状态', '生命周期', '来源批次', '操作'].map((name) => <th key={name} className="px-3 py-3">{name}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filteredProjects.map((project) => <tr key={project.id}><td className="px-3 py-3">{project.projectNo}</td><td className="px-3 py-3">{project.unit || '--'}</td><td className="px-3 py-3">{project.boiler || '--'}</td><td className="px-3 py-3">{project.wellNo}</td><td className="px-3 py-3">{project.plannedStartDate && project.plannedEndDate ? `${project.plannedStartDate} 至 ${project.plannedEndDate}` : project.scheduleStatus ? scheduleText[project.scheduleStatus] || project.scheduleStatus : '--'}</td><td className="px-3 py-3">{project.plannedSteam ?? '--'}</td><td className="px-3 py-3">{project.gasSupport || '--'}</td><td className="px-3 py-3">{planStatusText[project.planStatus] || project.planStatus}</td><td className="px-3 py-3">{lifecycleText[project.lifecycleStatus] || project.lifecycleStatus}</td><td className="px-3 py-3">{project.sourceImportId ? `批次 #${project.sourceImportId}` : '手工'}</td><td className="space-x-2 px-3 py-3">{project.planStatus === 'draft' && <button className="text-violet-700" onClick={() => action(project, 'plan-status', { status: 'issued' })}>下达</button>}{transitions[project.lifecycleStatus] && <button className="text-violet-700" onClick={() => action(project, 'transitions', { status: transitions[project.lifecycleStatus]!, actualDate: businessToday })}>进入{lifecycleText[transitions[project.lifecycleStatus]!]}</button>}</td></tr>)}{filteredProjects.length === 0 && <tr><td colSpan={11} className="px-3 py-5 text-slate-500">没有符合筛选条件的项目。</td></tr>}</tbody></table></div></section>
  </div>;
}
