import { useEffect, useState } from 'react';

type Project = { id: number; projectNo: string; wellNo: string; block: string; processType: string; plannedTransferDate: string; owner: string; planStatus: string; lifecycleStatus: string };
const transitions: Record<string, string | undefined> = { pending: 'injecting', injecting: 'soaking', soaking: 'pendingTransfer', pendingTransfer: 'producing', producing: 'closed' };

export function InjectionProjectManagement() {
  const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' });
  const load = () => void fetch('/api/injection-projects').then((r) => r.json()).then((payload) => { if (!payload.success) throw new Error(payload.message); setProjects(payload.data); }).catch((cause) => setError(cause.message || '项目加载失败'));
  useEffect(load, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/injection-projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } setForm({ wellNo: '', block: '', processType: '', plannedTransferDate: '', owner: '' }); load(); };
  const action = async (project: Project, endpoint: string, body: Record<string, string>) => { const response = await fetch(`/api/injection-projects/${project.id}/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!payload.success) { setError(payload.message); return; } load(); };
  return <div className="page-stack"><section className="app-card p-5"><h3 className="text-lg font-bold">新建注汽方案</h3><form className="mt-4 grid gap-3 md:grid-cols-5" onSubmit={create}>{(['wellNo', 'block', 'processType', 'plannedTransferDate', 'owner'] as const).map((field) => <input key={field} className="field-control" required type={field === 'plannedTransferDate' ? 'date' : 'text'} placeholder={{ wellNo: '井号', block: '区块', processType: '注汽工艺', plannedTransferDate: '计划转抽日', owner: '负责人' }[field]} value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} />)}<button className="action-button action-primary md:col-span-5">创建草拟方案</button></form>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section><section className="app-card overflow-hidden"><div className="app-card-header"><h3 className="font-bold">注汽项目</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>方案编号</th><th>井号</th><th>工艺</th><th>计划转抽</th><th>方案状态</th><th>项目状态</th><th>操作</th></tr></thead><tbody>{projects.map((project) => <tr key={project.id} className="border-t"><td>{project.projectNo}</td><td>{project.wellNo}</td><td>{project.processType}</td><td>{project.plannedTransferDate}</td><td>{project.planStatus}</td><td>{project.lifecycleStatus}</td><td className="space-x-2">{project.planStatus === 'draft' && <button onClick={() => action(project, 'plan-status', { status: 'issued' })}>下达</button>}{transitions[project.lifecycleStatus] && <button onClick={() => action(project, 'transitions', { status: transitions[project.lifecycleStatus]!, actualDate: new Date().toISOString().slice(0, 10) })}>进入{transitions[project.lifecycleStatus]}</button>}</td></tr>)}</tbody></table></div></section></div>;
}
